# Generated by Django 5.2.16 on 2026-09-19 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_track_cover_embedded_track_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PRIVATE', 'Private'), ('UNAVAILABLE', 'Unavailable'), ('DELETED', 'Deleted'), ('NEEDS_REVIEW', 'Needs review')], db_index=True, default='AVAILABLE', max_length=16),
        ),
    ]
