# Generated by Django 5.2.16 on 2026-09-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_youtube_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('PRIVATE', 'Private'), ('UNAVAILABLE', 'Unavailable'), ('DELETED', 'Deleted'), ('NEEDS_REVIEW', 'Needs review'), ('REJECTED', 'Rejected')], db_index=True, default='AVAILABLE', max_length=16),
        ),
    ]
