"""
Django settings for music_manager project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!aq7)-4^d*@jk%p_zo(-$s!=5#rv+x-&_(y!etrl4$sjr3-z-y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

# Only the apps this project actually uses: staticfiles (WhiteNoise assets),
# the playlist app, and DRF for the /api/ endpoints. The default admin/auth/
# sessions/messages/contenttypes apps were removed — there is no login, admin,
# or session usage anywhere in the code.
INSTALLED_APPS = [
    'django.contrib.staticfiles',
    'playlist',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files directly from the app process (gzip + far-future
    # caching), so no nginx is needed on the Pi. Must sit right after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# With django.contrib.auth removed, DRF must not reach for AnonymousUser or the
# session/basic authenticators (they import auth/contenttypes and would 500 every
# API request). The API is unauthenticated and open, matching prior behaviour.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.AllowAny'],
    'UNAUTHENTICATED_USER': None,
}

ROOT_URLCONF = 'music_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'music_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'init_command': (
                'PRAGMA journal_mode=WAL;'
                'PRAGMA synchronous=NORMAL;'
                'PRAGMA busy_timeout=5000;'
            ),
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# collectstatic gathers everything here for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: compress assets and serve them with long-lived cache headers.
# CompressedStaticFilesStorage (no hashed manifest) keeps things simple — the
# vendored bootstrap-icons CSS references its font files with relative URLs.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        # time | level | source | thread | message
        # `name` separates the web server ("django") from the job workers ("worker");
        # `threadName` identifies each worker thread (worker-1, worker-2, …).
        "clean": {
            "format": "{asctime} [{levelname}] {name:<6} {threadName:<11} ({filename}::{lineno}) {message}",
            "datefmt": "%Y-%m-%d %H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "clean"},
        "server_file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "django.log",
            "formatter": "clean",
            "encoding": "utf-8",
        },
        "worker_file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "worker.log",
            "formatter": "clean",
            "encoding": "utf-8",
        },
    },
    "loggers": {
        # Web server / views / SSE  ->  console + django.log
        "django": {
            "handlers": ["console", "server_file"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        # Background workers + job/download/tag services  ->  console + worker.log
        "worker": {
            "handlers": ["console", "worker_file"],
            "level": os.getenv("WORKER_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}


PLAYLIST_URL = str(os.environ["PLAYLIST_URL"]).strip().strip('\"\'')

OUTPUT_DIRECTORY = os.getenv("OUTPUT_DIRECTORY", "/media/pi/500gb hdd/Youtube_Music/playlist_sync_django")

GEMINI_API_KEY = str(os.environ["GEMINI_API_KEY"]).strip().strip('\"\'')


# yt-dlp / venv locations on the host (used by the "update yt-dlp" action + version badge).
YTDLP_PATH = os.getenv("YTDLP_PATH", "/home/pi/Desktop/py_music_manager/.venv/bin/yt-dlp")
PIP_PATH = os.getenv("PIP_PATH", "/home/pi/Desktop/py_music_manager/.venv/bin/pip")
PROJECT_BASE_DIR = os.getenv("PROJECT_BASE_DIR", "/home/pi/Desktop/py_music_manager")
SYSTEMD_SERVICE = os.getenv("SYSTEMD_SERVICE", "music_manager")

# Inline background workers (threads inside the web process) + SSE tuning
WORKER_THREADS = int(os.getenv("WORKER_THREADS", "2"))          # job concurrency (keep gunicorn --workers 1)
WORKER_POLL_SECONDS = float(os.getenv("WORKER_POLL_SECONDS", "2"))
WORKER_COOLDOWN_SECONDS = float(os.getenv("WORKER_COOLDOWN_SECONDS", "5"))
SSE_POLL_SECONDS = float(os.getenv("SSE_POLL_SECONDS", "5"))

# Periodic auto-sync: every N minutes, refresh the playlist and queue downloads
SYNC_INTERVAL_MINUTES = int(os.getenv("SYNC_INTERVAL_MINUTES", "30"))