# Generated by Django 5.2.5 on 2025-08-30 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(help_text='YouTube video ID', max_length=11, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('uploader', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('url', models.URLField(max_length=2048, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('PRIVATE', 'Private')], default='AVAILABLE', max_length=20)),
                ('last_check_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalTrack',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='local_track', serialize=False, to='playlist.video')),
                ('local_path', models.CharField(blank=True, help_text='The absolute path to the local mp3 file.', max_length=512)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending Download'), ('DOWNLOADING', 'Downloading'), ('DOWNLOADED', 'Downloaded, Awaiting Tagging'), ('TAGGING', 'Tagging with Shazam'), ('COMPLETED', 'Processing Complete'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('md5_hash', models.CharField(blank=True, max_length=32, null=True)),
                ('retry_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local Audio Track',
                'ordering': ['-created_at'],
            },
        ),
    ]
