# Generated by Django 5.2.5 on 2025-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localtrack',
            name='local_path',
            field=models.CharField(blank=True, help_text='The absolute path to the local mp3 file.', max_length=1024),
        ),
    ]
