# Generated by Django 5.2.5 on 2025-08-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_alter_localtrack_local_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('PRIVATE', 'Private'), ('DELETED', 'Deleted')], default='AVAILABLE', max_length=20),
        ),
    ]
