# Generated by Django 5.2.14 on 2026-07-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_video_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('RESYNC', 'Resync playlist'), ('DOWNLOAD', 'Download + tag video'), ('TAG_ALL', 'Process pending tagging'), ('DELETE', 'Delete local track'), ('UPDATE_YTDLP', 'Update yt-dlp'), ('AUTO_SYNC', 'Auto-sync + download')], max_length=20)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='QUEUED', max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Progress note or error detail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='playlist.video')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='playlist_jo_status_b26453_idx')],
            },
        ),
    ]
